name: XML Validation

on:
  push:
    branches:
    - master
  pull_request:

permissions:
  contents: read

jobs:
  ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt install libxml2-utils
    - name: Lint translations
      run: |
        ./validate.sh

